# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_demande_index:
    path: /demande
    controller: App\Controller\DemandeController::index
    methods: GET

app_demande_new:
    path: /demande/new
    controller: App\Controller\DemandeController::new
    methods: [GET, POST]

app_demande_show:
    path: /demande/{id}
    controller: App\Controller\DemandeController::show
    methods: GET

app_demande_edit:
    path: /demande/{id}/edit
    controller: App\Controller\DemandeController::edit
    methods: [GET, POST]

app_demande_delete:
    path: /demande/{id}
    controller: App\Controller\DemandeController::delete
    methods: POST

app_demande_accept:
    path: /demande/{id}/accept
    controller: App\Controller\DemandeController::accept
    methods: POST

app_demande_refuse:
    path: /demande/{id}/refuse
    controller: App\Controller\DemandeController::refuse
    methods: POST
